export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";
export const RECEIVE_MOVIES = "RECEIVE_MOVIES";

export const RECEIVE_SEARCH = "RECEIVE_SEARCH"

export const RECEIVE_DETAILS = "RECEIVE_DETAILS";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";

export const RECEIVE_GENRES = "RECEIVE_GENRES";
export const CHANGE_GENRES = "CHANGE_GENRES";
export const SORT_BY = "SORT_BY";
export const RECEIVE_CREDITS = "RECEIVE_CREDITS";