export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";
export const RECEIVE_MOVIES = "RECEIVE_MOVIES";

export const RECEIVE_SEARCH = "RECEIVE_SEARCH"

export const RECEIVE_DETAILS = "RECEIVE_DETAILS";